[package]
name = "assert-offset"
version = "0.1.1"
edition = "2021"
description = "Derive macro for asserting the memory offset of fields in a struct."
repository = "https://github.com/cohaereo/assert-offset"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.38"
syn = "2.0.96"
